version: '3.6'

services:
  bootstrap:
#    image: harbor-gn2.cicd.s15m.nl/koop-lvbb-docker-hub/marklogicdb/marklogic-db:10.0-10.2-centos-1.0.2
    image: harbor-gn2.cicd.s15m.nl/koop-lvbb-docker-hub/marklogicdb/marklogic-db:latest-11
    hostname: schemas.db
    container_name: schemas.db
    dns_search: ""
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - TZ=Europe/Amsterdam
    volumes:
      - ./logs:/var/opt/MarkLogic/Logs:delegated
      - ./data:/data
      - cds_data:/var/opt/MarkLogic
    ports:
      - 7997-7999:7997-7999
      - 8000-8002:8000-8002
      - 8010-8013:8010-8013
    networks:
    - external_net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    extra_hosts:
      host.docker.internal: host-gateway

networks:
  external_net: {}

volumes:
  cds_data: