= schematron-test
:source-highlighter: rouge
:source-language: xslt
:icons: font

*Adjust MarkLogic Schematron validation so it can accept parameters during schematron transformation*

Did you ever wonder if it is possible to pass in external parameters during a schematron validation?

With the default iso-schematron it is not possible out-of-the-box. +
But as a schematron validation is in effect an xslt transformation, you should be able to pass in external parameters which can be used in a schematron rule/assert or report.

This project describes how to extend the default ISO Schematron implementation so it accepts external parameters in teh validation process.

It uses docker compose to set up a docker container with a MarkLogic 10.0-10.2 installation and gradle to deploy the MarkLogic application.

*Start Docker container

Make sure docker is installed on your local development environment.+
Execute the following command in a terminal to start the docker container:

```
docker compose up -d
```

Execute the following command in a terminal to stop the docker container:
```
docker compose stop
```

Execute the following command in a terminal to remove the container and its volumes:
```
docker compose down --volumes
```

*Install the test application

