= schematron-test
:source-highlighter: rouge
:source-language: xslt
:icons: font

*Adjust MarkLogic Schematron validation so it can accept parameters during schematron transformation*

Did you ever wonder if it is possible to pass in external parameters during a schematron validation?

With the default iso-schematron it is not possible out-of-the-box. +
But as a schematron validation is in effect an xslt transformation, you should be able to pass in external parameters which can be used in a schematron rule/assert or report.

This project describes how to extend the default ISO Schematron implementation so it accepts external parameters in teh validation process.

It uses docker compose to set up a docker container with a MarkLogic 10.0-10.2 installation and gradle to deploy the MarkLogic application.

== Start Docker container

Make sure docker is installed on your local development environment.+
Execute the following command in a terminal to start the docker container:

```
docker compose up -d
```

Execute the following command in a terminal to stop the docker container:
```
docker compose stop
```

Execute the following command in a terminal to remove the container and its volumes:
```
docker compose down --volumes
```

== Install the test application

Execute te following command in a terminal to install the test application.

```
gradlew mlDeploy -i
```

This will also load the schemas and schematrons in the ml-data folder and it will processes the schemas and schematrons by replacing all schemaLocation attributes in the schemas and schematrons (if there are any) with values from the catalog files (if present).
All schemas and schematrons will be copied to the schemas database. All schematrons will be precompiled and stored in the modules database.

The schemas and schematrons can contain schemaLocations like below:
[source, xml]
----
<xs:schema elementFormDefault="qualified"
  targetNamespace="https://standaarden.overheid.nl/lvbb/stop/aanlevering/" version="1.2.0"
  xmlns:data="https://standaarden.overheid.nl/stop/imop/data/"
  xmlns:gio="https://standaarden.overheid.nl/stop/imop/gio/"
  xmlns:imop="https://standaarden.overheid.nl/stop/imop/"
  xmlns:lvbba="https://standaarden.overheid.nl/lvbb/stop/aanlevering/"
  xmlns:se="http://www.opengis.net/se"
  xmlns:tekst="https://standaarden.overheid.nl/stop/imop/tekst/"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  ...
  <xs:import namespace="https://standaarden.overheid.nl/stop/imop/data/"
    schemaLocation="https://standaarden.overheid.nl/stop/1.3.0/imop-data.xsd" />
  <xs:import namespace="https://standaarden.overheid.nl/stop/imop/tekst/"
    schemaLocation="https://standaarden.overheid.nl/stop/1.3.0/imop-tekst.xsd" />
  <xs:import namespace="http://www.opengis.net/se"
    schemaLocation="https://standaarden.overheid.nl/stop/1.3.0/se-FeatureStyle-imop.xsd" />
  <xs:import namespace="https://standaarden.overheid.nl/stop/imop/gio/"
    schemaLocation="https://standaarden.overheid.nl/stop/1.3.0/imop-gio.xsd" />
  ...
</xs:schema>
----

The catalogs contain entries like below:
[source, xml]
----
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  ...
  <uri name="https://standaarden.overheid.nl/stop/1.3.0/imop-bedrijfsregels.xsd" uri="imop-bedrijfsregels.xsd"/>
  <uri name="https://standaarden.overheid.nl/stop/1.3.0/imop-consolidatie.xsd" uri="imop-consolidatie.xsd"/>
  <uri name="https://standaarden.overheid.nl/stop/1.3.0/imop-data.xsd" uri="imop-data.xsd"/>
  <uri name="https://standaarden.overheid.nl/stop/1.3.0/imop-geo.xsd" uri="imop-geo.xsd"/>
  <uri name="https://standaarden.overheid.nl/stop/1.3.0/imop-gio.xsd" uri="imop-gio.xsd"/>
  <uri name="https://standaarden.overheid.nl/stop/1.3.0/imop-resources.xsd" uri="imop-resources.xsd"/>
  <uri name="https://standaarden.overheid.nl/stop/1.3.0/imop-schemata.xsd" uri="imop-schemata.xsd"/>
  <uri name="https://standaarden.overheid.nl/stop/1.3.0/imop-tekst.xsd" uri="imop-tekst.xsd"/>
  <uri name="https://standaarden.overheid.nl/stop/1.3.0/imop-uitwisseling.xsd" uri="imop-uitwisseling.xsd"/>
  ...
</catalog>
----

When an absolute schemaLocation is found in one of the schemas/schematrons and it is also found in any of the catalogs in a uri/@name it will be replaced by an absolute uri location based on the catalog location in MarkLogic followed by the uri/@uri.+
All relative schemaLocations will be replaced by an absolute uri location in MarkLogic.

